### ISSUE TITLE
LoRA

### ISSUE THREAD

**Issue by MOGRAINEREPORTS** [bedovyy/chibi-client#3]
Plugin still works, idk if anyone plans to touch it but possibility of LORAS would be great, thanks

**Comment by bedovyy** [comment]
sorry for late response.

I am waiting this PR and after applying this, you can use lora from prompt.
(I will autocomplete the list of lora)
https://github.com/comfyanonymous/ComfyUI/pull/2666?ref=blog.comfy.org

Please wait more, sorry.

**Comment by bedovyy** [comment]
it supports lora, finally. so sorry for long waiting.
pleae try and let me know if there's issue.
